apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-payment-api
  labels:
    app: eos-payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-payment-api
  template:
    metadata:
      labels:
        app: eos-payment-api
    spec:
      containers:
      - name: eos-payment-api
        image: docker.io/dpthub/eos-payment-api:latest
        ports:
        - containerPort: 8083
